# Generated by Django 3.1.4 on 2021-03-02 15:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('uuid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.TextField()),
                ('pic', models.FileField(upload_to='')),
                ('isCovid', models.CharField(default='No', max_length=3)),
                ('check_date', models.DateField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CovidDetect.user')),
            ],
        ),
    ]
